var  userModel = require('../models/user');
module.exports = {
    /*
        Will be translated to get("/user") (first level is generated by controller name)
    */
    get_index : function(req, res) {
        //寻找模型方法
        var msg = userModel.test();
        res.send(msg);
    },
    get_user : function(req, res) {
        // var msg = userModel.test();
        // res.send(msg);
        var arr;
        userModel.showUser(req,res,function(err,result) {
            arr =JSON.parse(result);
            // console.log(result)

        });
        console.log(arr);
        // res.render('userShow',{user :arr});
    }
}